### ISSUE TITLE
Arbitrary code execution

### ISSUE THREAD

**Issue by travishathaway** [Greg-Boggs/css-complexity#1]
It looks like the $url variable in "scan.php" allows for arbitrary code execution. (https://github.com/Greg-Boggs/css-complexity/blob/master/scan.php#L67)

For example, visit the follwoing URL and notice the effect on page load:

http://css.gregboggs.com/scan.php?url=http://google.com/;sleep+20

I haven't done any PHP in a while, but I think this is what you want: http://php.net/manual/en/function.escapeshellarg.php

**Comment by Greg-Boggs** [comment]
Thanks!

Fixed (and commented out as intended). 

Although, my "wash_url" function really needs to be finished. It should ensure that the user input is a valid domain name and reject anything that's not. ... so ; should be rejected... care to take a crack at a pull request? 

Hrm, my URL preg match doesn't appear to be doing anything...

**Comment by Greg-Boggs** [comment]
Maybe I'll just run this on input first: http://php.net/htmlspecialchars

My plan was to add this: http://php.net/manual/en/mysqli.real-escape-string.php once I add the history graph, but that might muck with some valid urls.

**Comment by Greg-Boggs** [comment]
Ok, I believe I have it sorted. Feel free to reopen if I'm wrong!
